# Nome da aplicação
spring.application.name=consent-api

# Conexão com o MongoDB local que subimos no Docker
spring.data.mongodb.uri=mongodb://localhost:27017/consent_db

# Configuração para o Swagger aparecer na raiz (opcional, mas facilita)
springdoc.swagger-ui.path=/swagger-ui.html